
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jsant
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonComprobar = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        TextRed2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextRed3 = new javax.swing.JTextField();
        TextRed4 = new javax.swing.JTextField();
        TextPrueba303 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TextMascara1 = new javax.swing.JTextField();
        TextMascara2 = new javax.swing.JTextField();
        TextMascara3 = new javax.swing.JTextField();
        TextMascara4 = new javax.swing.JTextField();
        TextPrueba101 = new javax.swing.JTextField();
        TextPrueba102 = new javax.swing.JTextField();
        TextPrueba103 = new javax.swing.JTextField();
        TextPrueba104 = new javax.swing.JTextField();
        TextPrueba201 = new javax.swing.JTextField();
        TextPrueba202 = new javax.swing.JTextField();
        TextPrueba203 = new javax.swing.JTextField();
        TextPrueba204 = new javax.swing.JTextField();
        TextPrueba301 = new javax.swing.JTextField();
        TextPrueba401 = new javax.swing.JTextField();
        TextPrueba302 = new javax.swing.JTextField();
        TextPrueba402 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        TextRed1 = new javax.swing.JTextField();
        TextPrueba403 = new javax.swing.JTextField();
        TextPrueba304 = new javax.swing.JTextField();
        TextPrueba404 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        binario1 = new javax.swing.JTextField();
        binario2 = new javax.swing.JTextField();
        LabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Red 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 70, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Mascara");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 100, -1));

        BotonComprobar.setBackground(new java.awt.Color(0, 0, 204));
        BotonComprobar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonComprobar.setForeground(new java.awt.Color(255, 255, 255));
        BotonComprobar.setText("Comprobar");
        BotonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprobarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonComprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 130, 40));

        BotonLimpiar.setBackground(new java.awt.Color(0, 0, 204));
        BotonLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 100, 40));

        TextRed2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextRed2.setText("168");
        TextRed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRed2ActionPerformed(evt);
            }
        });
        getContentPane().add(TextRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 50, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText(".");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 30));

        TextRed3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextRed3.setText("0");
        TextRed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRed3ActionPerformed(evt);
            }
        });
        getContentPane().add(TextRed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 50, -1));

        TextRed4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextRed4.setText("5");
        TextRed4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRed4ActionPerformed(evt);
            }
        });
        getContentPane().add(TextRed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 50, -1));

        TextPrueba303.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba303.setText("24");
        TextPrueba303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba303ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba303, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 50, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText(".");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText(".");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, 30));

        TextMascara1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextMascara1.setText("255");
        TextMascara1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMascara1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextMascara1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 50, -1));

        TextMascara2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextMascara2.setText("255");
        TextMascara2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMascara2ActionPerformed(evt);
            }
        });
        getContentPane().add(TextMascara2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 50, -1));

        TextMascara3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextMascara3.setText("255");
        TextMascara3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMascara3ActionPerformed(evt);
            }
        });
        getContentPane().add(TextMascara3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 50, -1));

        TextMascara4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextMascara4.setText("0");
        TextMascara4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMascara4ActionPerformed(evt);
            }
        });
        getContentPane().add(TextMascara4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 50, -1));

        TextPrueba101.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba101.setText("192");
        TextPrueba101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba101ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba101, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 50, -1));

        TextPrueba102.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba102.setText("168");
        TextPrueba102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba102ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba102, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 50, -1));

        TextPrueba103.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba103.setText("10");
        TextPrueba103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba103ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba103, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 50, -1));

        TextPrueba104.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba104.setText("5");
        TextPrueba104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba104ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba104, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 50, -1));

        TextPrueba201.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba201.setText("192");
        TextPrueba201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba201ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba201, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 50, -1));

        TextPrueba202.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba202.setText("168");
        TextPrueba202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba202ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba202, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 50, -1));

        TextPrueba203.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba203.setText("0");
        TextPrueba203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba203ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba203, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 50, -1));

        TextPrueba204.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba204.setText("22");
        TextPrueba204.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba204ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba204, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 50, -1));

        TextPrueba301.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba301.setText("10");
        TextPrueba301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba301ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba301, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 50, -1));

        TextPrueba401.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba401.setText("192");
        TextPrueba401.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba401ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba401, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 50, -1));

        TextPrueba302.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba302.setText("10");
        TextPrueba302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba302ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba302, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 50, -1));

        TextPrueba402.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba402.setText("168");
        TextPrueba402.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba402ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba402, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 50, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setText(".");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText(".");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setText(".");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setText(".");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setText(".");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setText(".");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setText(".");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setText(".");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel20.setText(".");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setText(".");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel22.setText(".");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel23.setText(".");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel24.setText(".");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel25.setText(".");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, -1, 30));

        TextRed1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextRed1.setText("192");
        TextRed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRed1ActionPerformed(evt);
            }
        });
        getContentPane().add(TextRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 50, -1));

        TextPrueba403.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba403.setText("0");
        TextPrueba403.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba403ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba403, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 50, -1));

        TextPrueba304.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba304.setText("0");
        TextPrueba304.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba304ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba304, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 50, -1));

        TextPrueba404.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TextPrueba404.setText("0");
        TextPrueba404.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrueba404ActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrueba404, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 50, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel26.setText(".");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 30));

        BotonSalir.setBackground(new java.awt.Color(204, 0, 0));
        BotonSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("RED");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Red 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Red 4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 70, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Red 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 70, -1));
        getContentPane().add(binario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 270, 30));
        getContentPane().add(binario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 280, 30));

        LabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(LabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprobarActionPerformed
        // TODO add your handling code here:
        String res1 = "";
        String res2 = "";
        String bin1 = "";
        String bin2 = "";
        
        bin1 = Conversor(Integer. parseInt(TextRed1.getText()));
        bin1 = bin1 + ".";
        bin1 = bin1 + Conversor(Integer. parseInt(TextRed2.getText()));
        bin1 = bin1 + ".";
        bin1 = bin1 + Conversor(Integer. parseInt(TextRed3.getText()));
        bin1 = bin1 + ".";
        bin1 = bin1 + Conversor(Integer. parseInt(TextRed4.getText()));
        binario1.setText(bin1);
        
        bin2 = Conversor(Integer. parseInt(TextMascara1.getText()));
        bin2 = bin2 + ".";
        bin2 = bin2 + Conversor(Integer. parseInt(TextMascara2.getText()));
        bin2 = bin2 + ".";
        bin2 = bin2 + Conversor(Integer. parseInt(TextMascara3.getText()));
        bin2 = bin2 + ".";
        bin2 = bin2 + Conversor(Integer. parseInt(TextMascara4.getText()));
        binario2.setText(bin2);
        
        //String texto = TextPrueba101.getText();
        //int valor = Integer. parseInt(texto); 
        //texto = Conversor(valor);
        //res1 = texto;
        //texto = TextPrueba201.getText();
        //valor = Integer. parseInt(texto); 
        //texto = Conversor(valor);
        //res2 = texto;
        
        //texto = Operacion_And(res1,res2);
        //JOptionPane.showMessageDialog(null,
                //texto,
                //"PopUp Dialog",
                //JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_BotonComprobarActionPerformed

    private void TextRed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRed2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRed2ActionPerformed

    private void TextRed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRed3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRed3ActionPerformed

    private void TextRed4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRed4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRed4ActionPerformed

    private void TextPrueba303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba303ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba303ActionPerformed

    private void TextMascara1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMascara1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMascara1ActionPerformed

    private void TextMascara2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMascara2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMascara2ActionPerformed

    private void TextMascara3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMascara3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMascara3ActionPerformed

    private void TextMascara4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMascara4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMascara4ActionPerformed

    private void TextPrueba101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba101ActionPerformed

    private void TextPrueba102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba102ActionPerformed

    private void TextPrueba103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba103ActionPerformed

    private void TextPrueba104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba104ActionPerformed

    private void TextPrueba201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba201ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba201ActionPerformed

    private void TextPrueba202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba202ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba202ActionPerformed

    private void TextPrueba203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba203ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba203ActionPerformed

    private void TextPrueba204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba204ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba204ActionPerformed

    private void TextPrueba301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba301ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba301ActionPerformed

    private void TextPrueba401ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba401ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba401ActionPerformed

    private void TextPrueba302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba302ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba302ActionPerformed

    private void TextPrueba402ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba402ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba402ActionPerformed

    private void TextRed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRed1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRed1ActionPerformed

    private void TextPrueba403ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba403ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba403ActionPerformed

    private void TextPrueba304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba304ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba304ActionPerformed

    private void TextPrueba404ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrueba404ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrueba404ActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    public String Conversor(int num)
    {
        int numb = num;
        String binario = Integer.toBinaryString(numb);
        binario = String.format("%8s", binario).replace(" ", "0");
        return binario;
    }
    
    public String Operacion_And(String val1, String val2)
    {
       String Resultado = "";
       for(int i=0;i<8;i++)
       {
          
           if(val1.charAt(i)==val2.charAt(i) && val1.charAt(i)==49)
           {
               Resultado += "1";
           }
           else
           {
              Resultado += "0";
           }
       }
        
        return Resultado;
    }
    
    
    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        TextPrueba101.setText(null);
        TextPrueba102.setText(null);
        TextPrueba103.setText(null);
        TextPrueba104.setText(null);
        TextPrueba201.setText(null);
        TextPrueba202.setText(null);
        TextPrueba203.setText(null);
        TextPrueba204.setText(null);
        TextPrueba301.setText(null);
        TextPrueba302.setText(null);
        TextPrueba303.setText(null);
        TextPrueba304.setText(null);
        TextPrueba401.setText(null);
        TextPrueba402.setText(null);
        TextPrueba403.setText(null);
        TextPrueba404.setText(null);
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonComprobar;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel LabelFondo;
    private javax.swing.JTextField TextMascara1;
    private javax.swing.JTextField TextMascara2;
    private javax.swing.JTextField TextMascara3;
    private javax.swing.JTextField TextMascara4;
    private javax.swing.JTextField TextPrueba101;
    private javax.swing.JTextField TextPrueba102;
    private javax.swing.JTextField TextPrueba103;
    private javax.swing.JTextField TextPrueba104;
    private javax.swing.JTextField TextPrueba201;
    private javax.swing.JTextField TextPrueba202;
    private javax.swing.JTextField TextPrueba203;
    private javax.swing.JTextField TextPrueba204;
    private javax.swing.JTextField TextPrueba301;
    private javax.swing.JTextField TextPrueba302;
    private javax.swing.JTextField TextPrueba303;
    private javax.swing.JTextField TextPrueba304;
    private javax.swing.JTextField TextPrueba401;
    private javax.swing.JTextField TextPrueba402;
    private javax.swing.JTextField TextPrueba403;
    private javax.swing.JTextField TextPrueba404;
    private javax.swing.JTextField TextRed1;
    private javax.swing.JTextField TextRed2;
    private javax.swing.JTextField TextRed3;
    private javax.swing.JTextField TextRed4;
    private javax.swing.JTextField binario1;
    private javax.swing.JTextField binario2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
